# Schema for the configuration files of the Foodies theme.
foodiestheme.settings:
  type: theme_settings
  label: 'Foodies settings'
  mapping:
    font_size:
      type: integer
      label: Font size
